In [2]:
import tensorflow as tf

In [12]:
#Bai 1
tensor_5 = tf.ones([3,4])*5
print("Bài 1.1:\n", tensor_5.numpy())
random = tf.random.normal([2,2,2], mean = 0, stddev=1.0)
print("Bài 1.2:\n", random.numpy())
diag_tensor = tf.linalg.diag([1, 2, 3, 4])
print("Bài 1.3:\n", diag_tensor.numpy())


Bài 1.1:
 [[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]
Bài 1.2:
 [[[ 2.8670897   0.5201526 ]
  [-0.1277172  -1.4373133 ]]

 [[ 0.43513596 -0.38612887]
  [-1.5011033   1.0524379 ]]]
Bài 1.3:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
#Bai 2
tensor = tf.constant([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])
new_matrix = tensor[::2,:]
print("Bài 2.1:\n", new_matrix.numpy())

col_2 = tensor[::,1]
print("Bài 2.2:\n", col_2.numpy())

right_top_matrix = tensor[:2, 2:]
print("Bài 2.3:\n", right_top_matrix.numpy())

reshape_matrix = tf.reshape(tensor, [4 , 3])
print("Bài 2.4:\n", reshape_matrix.numpy())

Bài 2.1:
 [[ 1  2  3  4]
 [ 9 10 11 12]]
Bài 2.2:
 [ 2  6 10]
Bài 2.3:
 [[3 4]
 [7 8]]
Bài 2.4:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [31]:
#Bai 3
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

result1 = 2*a + b*b
print("Bài 3.1:\n", result1.numpy())

dot_product = tf.tensordot(a, b, axes=1)
print("Bài 3.2:\n", dot_product.numpy())

matrix = tf.cast(a, tf.float32)
det_a = tf.linalg.det(matrix)
print("Bài 3.3:\n", det_a.numpy())

transpose_b = tf.transpose(b)
print("Bài 3.4:\n", transpose_b.numpy())

Bài 3.1:
 [[27 40]
 [55 72]]
Bài 3.2:
 [[19 22]
 [43 50]]
Bài 3.3:
 -2.0
Bài 3.4:
 [[5 7]
 [6 8]]


In [34]:
image = tf.random.uniform([256, 256, 3], maxval=255, dtype=tf.int32)

r_channel = image[:, :, 0]
g_channel = image[:, :, 1]
b_channel = image[:, :, 2]
print("Bài 4.1:\n", r_channel.numpy(), g_channel.numpy(), b_channel.numpy())

mean_r = tf.reduce_mean(tf.cast(r_channel, tf.float32))
mean_g = tf.reduce_mean(tf.cast(g_channel, tf.float32))
mean_b = tf.reduce_mean(tf.cast(b_channel, tf.float32))
print("Bài 4.2 - Mean values:\n", mean_r.numpy(), mean_g.numpy(), mean_b.numpy())

gray_scaled_image = 0.299 * tf.cast(r_channel, tf.float32) + \
             0.587 * tf.cast(g_channel, tf.float32) + \
             0.114 * tf.cast(b_channel, tf.float32)
print("Bài 4.3 - Grayscale shape:", gray_scaled_image.shape)

top_left_img = image[:128, :128]
top_right_img = image[:128, 128:]
bottom_left_img = image[128:, :128]
bottom_right_img = image[128:, 128:]
print("Bài 4.4 - Crop shapes:",
      top_left_img.shape, top_right_img.shape,
      bottom_left_img.shape, bottom_right_img.shape)

Bài 4.1:
 [[214  55 239 ... 247  98 114]
 [203 198 155 ...  26 247  77]
 [ 73 166   5 ... 205 192 188]
 ...
 [167  76  73 ... 192 238  21]
 [125 118  73 ...  39  65  34]
 [209 243  88 ... 103 233  87]] [[ 95 229 141 ...  56 112 244]
 [160  89  33 ...  24 222  74]
 [189 192 116 ...  75   3 227]
 ...
 [ 75 202 215 ... 143 166  68]
 [ 81  43 125 ...  64   3 173]
 [229  93 146 ...  22 232 117]] [[238 247 251 ... 175  40 154]
 [247  39 242 ...  95 162   2]
 [ 24 103  25 ...  58  57 134]
 ...
 [ 65  87  91 ... 245  50  77]
 [187   3  16 ...  74 210 218]
 [161 155 113 ... 222 130  46]]
Bài 4.2 - Mean values:
 127.16629 126.925934 126.76703
Bài 4.3 - Grayscale shape: (256, 256)
Bài 4.4 - Crop shapes: (128, 128, 3) (128, 128, 3) (128, 128, 3) (128, 128, 3)
