In [13]:
import tensorflow as tf

In [ ]:
#Bai 1
tensor_1d = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=tf.int32)
print(tensor_1d)

tensor_2d = tf.reshape(tensor_1d,(3,3))
print(f"Reshape:\n{tensor_2d}")

tensor_3d = tf.expand_dims(tensor_2d, axis=0)
print(f"Expanded dims:\n{tensor_3d}")

x = tf.constant([[1, 2], [3, 4]])
y = tf.constant([[5, 6], [7, 8]])
stacked = tf.stack([x, y], axis=0)
print("Stacked:\n", stacked)

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)
Reshape:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Expanded dims:
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Stacked:
 tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [29]:
#Bai 2
A = tf.constant([[1,2],[3,4]], dtype=tf.int32)
B = tf.constant([[5,6],[7,8]], dtype=tf.int32)

stacked = tf.stack([A, B], axis=0)
print("Stacked (0):\n", stacked)

concat0 = tf.concat([A,B], axis=0)
print("Concatenated vertical:\n", concat0)

concat1 = tf.concat([A,B], axis=1)
print("concatenated Horizontal:\n", concat1)



Stacked (0):
 tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
Concatenated vertical:
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)
concatenated Horizontal:
 tf.Tensor(
[[1 2 5 6]
 [3 4 7 8]], shape=(2, 4), dtype=int32)


In [ ]:
#Bai 3
rt = tf.ragged.constant([[1,2], [3], [], [4,5,6]])

print("Giá trị truy xuất vị trí 2:", rt[2])
print("Giá trị truy xuất vị trí 3:", rt[3])

for i, row in enumerate(rt):
    print(f"Tổng hàng {i}:", tf.reduce_sum(row))

Giá trị truy xuất vị trí 2: tf.Tensor([], shape=(0,), dtype=int32)
Giá trị truy xuất vị trí 3: tf.Tensor([4 5 6], shape=(3,), dtype=int32)
Tổng hàng 0: tf.Tensor(3, shape=(), dtype=int32)
Tổng hàng 1: tf.Tensor(3, shape=(), dtype=int32)
Tổng hàng 2: tf.Tensor(0, shape=(), dtype=int32)
Tổng hàng 3: tf.Tensor(15, shape=(), dtype=int32)


In [ ]:
#Bai 4
sparse = tf.sparse.SparseTensor (
    indices = [[0, 2], [2, 0]],
    values = [5, 10],
    dense_shape = [3, 3]
)

dense_tensor = tf.sparse.to_dense(sparse)
print("Dense tensor:\n", dense_tensor)

print("Giá trị tại (0,2):", dense_tensor[0, 2])
print("Giá trị tại (2,0):", dense_tensor[2, 0])

Dense tensor:
 tf.Tensor(
[[ 0  0  5]
 [ 0  0  0]
 [10  0  0]], shape=(3, 3), dtype=int32)
Element at (0,2): tf.Tensor(5, shape=(), dtype=int32)
Element at (2,0): tf.Tensor(10, shape=(), dtype=int32)


In [41]:
#Bai 5
text = tf.constant("Machine learning is fun!")

words = tf.strings.split(text)
print("Từ sau khi tách:", words.numpy())

replaced = tf.strings.regex_replace(text, "fun", "powerful")
print("String sau khi thay đổi:", replaced.numpy())

var = tf.Variable([1.0, 2.0, 3.0])
var.assign_add([2.0, 2.0, 2.0])
print("Var new:", var.numpy())

Từ sau khi tách: [b'Machine' b'learning' b'is' b'fun!']
String sau khi thay đổi: b'Machine learning is powerful!'
Var new: [3. 4. 5.]
